import { Session } from './types';

export const initialSessions: Session[] = [
  {
    id: "1",
    title: "Sessão Diurna",
    timeRange: "08:00 às 12:00",
    days: "Segunda a Sábado",
    tasks: [
      { id: "t1", title: "Conversar com o Live do Gemini sobre os tópicos do dia anterior da disciplina 1", durationMinutes: 15, type: "Revisão" },
      { id: "t2", title: "Conversar com o Live do Gemini sobre os tópicos do dia anterior da disciplina 2", durationMinutes: 15, type: "Revisão" },
      { id: "t3", title: "Resolução de questões no QC sobre os tópicos do dia anterior da disciplina 1", durationMinutes: 12, type: "Resolução" },
      { id: "t4", title: "Resolução de questões no QC sobre os tópicos do dia anterior da disciplina 2", durationMinutes: 12, type: "Resolução" },
      { id: "t5", title: "Das questões erradas pedir à IA a teoria dos conteúdos que errei", durationMinutes: 5, type: "Teoria" },
      { id: "t6", title: "Ler a teoria dos conteúdos que errei para reforçar", durationMinutes: 30, type: "Teoria" },
      { id: "t7", title: "Escrever em folha branca o que aprendi (disciplina 1)", durationMinutes: 10, type: "Revisão" },
      { id: "t8", title: "Escrever em folha branca o que aprendi (disciplina 2)", durationMinutes: 11, type: "Revisão" }
    ]
  },
  {
    id: "2",
    title: "Sessão Noturna",
    timeRange: "21:00 às 00:00",
    days: "Segunda a Sábado",
    tasks: [
      { id: "n1", title: "Estudo da Teoria - Disciplina 3", durationMinutes: 50, type: "Teoria" },
      { id: "n2", title: "Pausa", durationMinutes: 10, type: "Pausa" },
      { id: "n3", title: "Estudo da Teoria - Disciplina 4", durationMinutes: 50, type: "Teoria" },
      { id: "n4", title: "Resolução de questões no QC - Disciplina 3", durationMinutes: 15, type: "Resolução" },
      { id: "n5", title: "Resolução de questões no QC - Disciplina 4", durationMinutes: 15, type: "Resolução" }
    ]
  }
];

export const topicsData = {
  "Português": [
    "Aula 00 - Apresentação do Curso",
    "Aula 00 - Noções Iniciais de Ortografia",
    "Aula 00 - Sons, Letras, Fonemas, Dígrafos",
    "Aula 00 - Encontros Vocálicos",
    "Aula 00 - Regras Gerais de Acentuação",
    "Aula 00 - Acentuação do Hiato",
    "Aula 00 - Acentos Diferenciais",
    "Aula 00 - Emprego do Hífen",
    "Aula 00 - Emprego das Letras",
    "Aula 00 - Uso de Letras Maiúsculas e Minúsculas",
    "Aula 00 - Siglas e Abreviações",
    "Aula 00 - Expressões Problemáticas",
    "Aula 00 - Outras regras Ortográficas Relevantes",
    "Aula 01 - Noções iniciais de Classes de Palavras I",
    "Aula 01 - Classes variáveis e invariáveis",
    "Aula 01 - Substantivo",
    "Aula 01 - Adjetivo",
    "Aula 01 - Expressões com Substantivo e Adjetivo",
    "Aula 01 - Advérbio",
    "Aula 01 - Artigo",
    "Aula 01 - Numeral",
    "Aula 01 - Interjeição",
    "Aula 01 - Palavras especiais",
    "Aula 02 - Noções Iniciais de Classes de Palavras II",
    "Aula 02 - Preposições",
    "Aula 02 - Conjunções",
    "Aula 03 - Noções iniciais de pronomes",
    "Aula 03 - Pronomes",
    "Aula 03 - Colocação Pronominal",
    "Aula 04 - Noções iniciais de Verbos",
    "Aula 04 - Emprego de tempos e modos verbais",
    "Aula 04 - Modo indicativo",
    "Aula 04 - Modo subjuntivo",
    "Aula 04 - Modo imperativo",
    "Aula 04 - Formas nominais do verbo",
    "Aula 04 - Transitividade verbal",
    "Aula 04 - Classificação dos verbos",
    "Aula 05 - Noções iniciais - Correlação e vozes verbais",
    "Aula 05 - Correlação dos tempos verbais",
    "Aula 05 - Locução verbal x Tempo Composto",
    "Aula 05 - Vozes verbais",
    "Aula 06 - Sintaxe - Noções iniciais",
    "Aula 06 - Funções Sintáticas",
    "Aula 06 - Frase x Oração x Período",
    "Aula 07 - Noções Iniciais - Sintaxe do período",
    "Aula 07 - Coordenação e Subordinação",
    "Aula 07 - Orações Coordenadas",
    "Aula 07 - Orações Subordinadas Substantivas",
    "Aula 07 - Orações Subordinadas Adjetivas",
    "Aula 07 - Orações Subordinadas Adverbiais",
    "Aula 07 - Oração Reduzida e Oração Desenvolvida",
    "Aula 07 - Paralelismo",
    "Aula 07 - Palavra QUE",
    "Aula 07 - Palavra SE",
    "Aula 07 - Palavra COMO",
    "Aula 08 - Noções Iniciais de Pontuação",
    "Aula 08 - Vírgula, Respiração e Semântica",
    "Aula 08 - Uso da Vírgula",
    "Aula 08 - Ponto e Vírgula",
    "Aula 08 - Dois-pontos",
    "Aula 08 - Reticências",
    "Aula 08 - Aspas",
    "Aula 08 - Travessão",
    "Aula 08 - Parênteses",
    "Aula 08 - Ponto final",
    "Aula 09 - Noções Iniciais de Concordância",
    "Aula 09 - Tipos de Sujeito",
    "Aula 09 - Concordância com Sujeito simples",
    "Aula 09 - Concordância com Sujeito composto",
    "Aula 09 - Concordância do Verbo SER",
    "Aula 09 - Concordância Nominal",
    "Aula 10 - Noções Iniciais de Regência e Crase",
    "Aula 10 - Regência Verbal",
    "Aula 10 - Regência Nominal",
    "Aula 10 - Crase",
    "Aula 11 - Noções Iniciais de Coesão e Coerência",
    "Aula 11 - Coesão Textual",
    "Aula 11 - Coerência",
    "Aula 11 - Reescritura",
    "Aula 12 - Noções iniciais de Semântica",
    "Aula 12 - Campo semântico",
    "Aula 12 - Sentido Denotativo e Sentido Conotativo",
    "Aula 12 - Sinônimos e Antônimos",
    "Aula 12 - Hiperônimo e Hipônimo",
    "Aula 12 - Homônimos e Parônimos",
    "Aula 12 - Polissemia",
    "Aula 12 - Ambiguidade",
    "Aula 12 - Homônimo, Polissemia e Ambiguidade",
    "Aula 13 - Noções Iniciais de Tipologia Textual",
    "Aula 13 - Tipo x Gênero",
    "Aula 13 - Narração",
    "Aula 13 - Descrição",
    "Aula 13 - Injunção",
    "Aula 13 - Dissertação",
    "Aula 13 - Funções da Linguagem",
    "Aula 13 - Noções Iniciais de Interpretação de Textos",
    "Aula 13 - Linguagem Verbal x Linguagem Não verbal",
    "Aula 13 - Linguagem Literária x Linguagem Não literária",
    "Aula 13 - Intertextualidade",
    "Aula 13 - Interpretação e Compreensão",
    "Aula 13 - Modalização discursiva",
    "Aula 13 - Julgamento de Assertivas",
    "Aula 14 - Noções Iniciais de Redação Oficial",
    "Aula 14 - Comunicação Oficial",
    "Aula 14 - Atributos da redação oficial",
    "Aula 14 - As Comunicações Oficiais",
    "Aula 14 - Estrutura do Padrão Ofício",
    "Aula 14 - Formatação do Padrão ofício",
    "Aula 14 - Tipos de Documentos",
    "Aula 14 - Exposição de Motivos",
    "Aula 14 - Mensagem",
    "Aula 14 - E-mail",
    "Aula 14 - Outros Expedientes"
  ],
  "Ética e Conduta do Servidor Público": [
    "Aula 01 - Apresentação - Ética e Moral",
    "Aula 01 - Ética",
    "Aula 01 - Juízos de Apreciação",
    "Aula 01 - A Pós-Verdade e sua Relação com a Ética",
    "Aula 01 - Principais Doutrinas Éticas",
    "Aula 01 - Ética e Filosofia",
    "Aula 01 - Moral",
    "Aula 01 - Gestão da Ética nas Empresas Públicas e Privadas",
    "Aula 01 - Ética e Diversidade",
    "Aula 01 - Ética e Responsabilidade Social",
    "Aula 01 - Visão Ética de Direitos Morais",
    "Aula 01 - Conduta, Princípios, Valores e Virtudes",
    "Aula 01 - Ética e Cidadania",
    "Aula 01 - Modernidade Líquida",
    "Aula 02 - Natureza do Decreto nº 1.171/1994",
    "Aula 02 - Das Comissões de Ética",
    "Aula 02 - Seção I - Das Regras Deontológicas",
    "Aula 02 - Seção II - Dos Principais Deveres do Servidor Público",
    "Aula 02 - Seção III - Das Vedações ao Servidor Público"
  ]
};
